Core Module SDK Documentation: bc_module_lcd
bc_module_lcd
Driver for lcd.
Data Structures
struct bc_module_lcd_framebuffer_t
Macros
#define BC_LCD_FRAMEBUFFER_SIZE (1 + ((1+16+1) * 128) + 1)
Typedefs
typedef struct
bc_module_lcd_framebuffer_t bc_module_lcd_framebuffer_t
Enumerations
enum bc_module_lcd_event_t { BC_MODULE_LCD_EVENT_DONE = 0 }
Callback events.
enum bc_module_lcd_rotation_t {
BC_MODULE_LCD_ROTATION_0 = 0,
BC_MODULE_LCD_ROTATION_90 = 1,
BC_MODULE_LCD_ROTATION_180 = 2,
BC_MODULE_LCD_ROTATION_270 = 3
}
Functions
void bc_module_lcd_init (bc_module_lcd_framebuffer_t *framebuffer)
Initialize lcd.
void bc_module_lcd_on (void)
Lcd on.
void bc_module_lcd_off (void)
Lcd off.
void bc_module_lcd_clear (void)
Lcd clear.
void bc_module_lcd_draw_pixel (int left, int top, bool value)
Lcd draw pixel.
int bc_module_lcd_draw_char (int left, int top, uint8_t ch)
Lcd draw char.
int bc_module_lcd_draw_string (int left, int top, char *str)
Lcd draw string.
void bc_module_lcd_update (void)
Lcd update, send data.
void bc_module_lcd_set_font (const tFont *font)
Lcd set font.
void bc_module_lcd_set_rotation (bc_module_lcd_rotation_t rotation)
Lcd set rotation.
bc_module_lcd_rotation_t bc_module_lcd_get_rotation (void)
Lcd get rotation.
Variables
const tFont Font
const tFont FontBig
bc_module_lcd_framebuffer_t _bc_module_lcd_framebuffer
Detailed Description
Driver for lcd.
Enumeration Type Documentation
enum bc_module_lcd_event_t
Callback events.
Enumerator
BC_MODULE_LCD_EVENT_DONE
Done event.
Definition at line 13 of file bc_module_lcd.h.
Function Documentation
int bc_module_lcd_draw_char (int left, int top, uint8_t ch)
Lcd draw char.
Parameters
[in] int left
[in] int top
[in] uint8_t ch
Returns
width of printed character
Definition at line 131 of file bc_module_lcd.c.
Referenced by bc_module_lcd_draw_string().
void bc_module_lcd_draw_pixel (int left, int top, bool value)
Lcd draw pixel.
Parameters
[in] int left
[in] int top
[in] bool value
Definition at line 79 of file bc_module_lcd.c.
Referenced by bc_module_lcd_clear(), and bc_module_lcd_draw_char().
int bc_module_lcd_draw_string (int left, int top, char * str)
Lcd draw string.
Parameters
[in] int left
[in] int top
[in] char *str
Returns
width of printed characters
Definition at line 190 of file bc_module_lcd.c.
bc_module_lcd_rotation_t bc_module_lcd_get_rotation (void)
Lcd get rotation.
Returns
bc_module_lcd_rotation_t
Definition at line 265 of file bc_module_lcd.c.
void bc_module_lcd_init (bc_module_lcd_framebuffer_t * framebuffer)
Initialize lcd.
Parameters
[in] bc_module_lcd_framebuffer_t framebuffer
Definition at line 33 of file bc_module_lcd.c.
void bc_module_lcd_set_font (const tFont * font)
Lcd set font.
Parameters
[in] tFont *font
Definition at line 255 of file bc_module_lcd.c.
void bc_module_lcd_set_rotation (bc_module_lcd_rotation_t rotation)
Lcd set rotation.
Parameters
[in] bc_module_lcd_rotation_t rotation
Definition at line 260 of file bc_module_lcd.c.