Core Module SDK Documentation: bc_opt3001
bc_opt3001
Driver for OPT3001 ambient light sensor.
Typedefs
typedef struct bc_opt3001_t bc_opt3001_t
OPT3001 instance.
Enumerations
enum bc_opt3001_event_t {
BC_OPT3001_EVENT_ERROR = 0,
BC_OPT3001_EVENT_UPDATE = 1
}
Callback events.
Functions
void bc_opt3001_init (bc_opt3001_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize OPT3001 driver.
void bc_opt3001_set_event_handler (bc_opt3001_t *self, void(*event_handler)(bc_opt3001_t *, bc_opt3001_event_t, void *), void *event_param)
Set callback function.
void bc_opt3001_set_update_interval (bc_opt3001_t *self, bc_tick_t interval)
Set measurement interval.
bool bc_opt3001_get_luminosity_raw (bc_opt3001_t *self, uint16_t *raw)
Get measured luminosity as raw value.
bool bc_opt3001_get_luminosity_lux (bc_opt3001_t *self, float *lux)
Get measured luminosity in lux.
Detailed Description
Driver for OPT3001 ambient light sensor.
Enumeration Type Documentation
enum bc_opt3001_event_t
Callback events.
Enumerator
BC_OPT3001_EVENT_ERROR
Error event.
BC_OPT3001_EVENT_UPDATE
Update event.
Definition at line 13 of file bc_opt3001.h.
Function Documentation
bool bc_opt3001_get_luminosity_lux (bc_opt3001_t * self, float * lux)
Get measured luminosity in lux.
Parameters
[in] self Instance
[in] lux Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 45 of file bc_opt3001.c.
Referenced by bc_module_climate_get_luminosity_lux(), and bc_tag_lux_meter_get_luminosity_lux().
bool bc_opt3001_get_luminosity_raw (bc_opt3001_t * self, uint16_t * raw)
Get measured luminosity as raw value.
Parameters
[in] self Instance
[in] raw Pointer to variable where result will be stored
Returns
true When value is valid
false When value is invalid
Definition at line 33 of file bc_opt3001.c.
Referenced by bc_opt3001_get_luminosity_lux(), and bc_tag_lux_meter_get_luminosity_raw().
void bc_opt3001_init (bc_opt3001_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize OPT3001 driver.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 10 of file bc_opt3001.c.
Referenced by bc_module_climate_init(), and bc_tag_lux_meter_init().
void bc_opt3001_set_event_handler (bc_opt3001_t * self, void(*)(bc_opt3001_t *, bc_opt3001_event_t, void *) event_handler, void * event_param)
Set callback function.
Parameters
[in] self Instance
[in] event_handler Function address
[in] event_param Optional event parameter (can be NULL)
Definition at line 22 of file bc_opt3001.c.
Referenced by bc_module_climate_init(), and bc_tag_lux_meter_set_event_handler().
void bc_opt3001_set_update_interval (bc_opt3001_t * self, bc_tick_t interval)
Set measurement interval.
Parameters
[in] self Instance
[in] interval Measurement interval
Definition at line 28 of file bc_opt3001.c.
Referenced by bc_module_climate_set_update_interval_lux_meter(), and bc_tag_lux_meter_set_update_interval().