BigClown Core Module Library: bc_pyq1648
bc_pyq1648
Driver for pyq1648 pir sensor.
Data Structures
struct bc_pyq1648_t
Typedefs
typedef struct bc_pyq1648_t bc_pyq1648_t
Enumerations
enum bc_pyq1648_event_t {
BC_PYQ1648_EVENT_ERROR = 0,
BC_PYQ1648_EVENT_MOTION = 1
}
enum bc_pyq1648_state_t {
BC_PYQ1648_STATE_ERROR = -1,
BC_PYQ1648_STATE_INITIALIZE = 0,
BC_PYQ1648_STATE_IGNORE = 1,
BC_PYQ1648_STATE_CHECK = 2
}
enum bc_pyq1648_sensitivity_t {
BC_PYQ1648_SENSITIVITY_LOW = 0,
BC_PYQ1648_SENSITIVITY_MEDIUM,
BC_PYQ1648_SENSITIVITY_HIGH,
BC_PYQ1648_SENSITIVITY_VERY_HIGH
}
Functions
void bc_pyq1648_init (bc_pyq1648_t *self, bc_gpio_channel_t gpio_channel_serin, bc_gpio_channel_t gpio_channel_dl)
Initialize pyq1648 on channels gpio_channel_serin and gpio_channel_dl.
void bc_pyq1648_set_event_handler (bc_pyq1648_t *self, void(*event_handler)(bc_pyq1648_t *, bc_pyq1648_event_t))
Set pyq1648 event handler.
void bc_pyq1648_set_sensitivity (bc_pyq1648_t *self, bc_pyq1648_sensitivity_t sensitivity)
Set pyq1648 set sensitivity.
void bc_pyq1648_set_blank_period (bc_pyq1648_t *self, uint16_t blank_period)
Set pyq1648 set blank period.
Detailed Description
Driver for pyq1648 pir sensor.
Function Documentation
void bc_pyq1648_init (bc_pyq1648_t * self, bc_gpio_channel_t gpio_channel_serin, bc_gpio_channel_t gpio_channel_dl)
Initialize pyq1648 on channels gpio_channel_serin and gpio_channel_dl.
Parameters
[in] self PIR image
[in] gpio_channel_serin PIR serin channel
[in] gpio_channel_dl PIR dl channel
Definition at line 73 of file bc_pyq1648.c.
Referenced by bc_pir_module_init().
void bc_pyq1648_set_blank_period (bc_pyq1648_t * self, uint16_t blank_period)
Set pyq1648 set blank period.
Parameters
[in] self pyq1648 image
[in] bc_pyq1648_sensitivity_t blanj period in ms
Definition at line 107 of file bc_pyq1648.c.
void bc_pyq1648_set_event_handler (bc_pyq1648_t * self, void(*)(bc_pyq1648_t *, bc_pyq1648_event_t) event_handler)
Set pyq1648 event handler.
Parameters
[in] self pyq1648 image
[in] event_handler pyq1648 event handler
Definition at line 92 of file bc_pyq1648.c.
Referenced by bc_pir_module_set_event_handler().
void bc_pyq1648_set_sensitivity (bc_pyq1648_t * self, bc_pyq1648_sensitivity_t sensitivity)
Set pyq1648 set sensitivity.
Parameters
[in] self pyq1648 image
[in] event_handler pyq1648 event handler
Definition at line 98 of file bc_pyq1648.c.
Referenced by bc_pir_module_set_sensitivity().