Core Module SDK Documentation: bc_i2c
bc_i2c
Driver for I2C bus.
Data Structures
struct bc_i2c_tranfer_t
I2C transfer parameters.
Macros
#define BC_I2C_MEMORY_ADDRESS_16_BIT 0x80000000UL
This flag extends I2C transfer memory address from 8-bit to 16-bit.
Enumerations
enum bc_i2c_channel_t {
BC_I2C_I2C0 = 0L,
BC_I2C_I2C1 = 1L
}
I2C channels.
enum bc_i2c_speed_t {
BC_I2C_SPEED_100_KHZ = 0L,
BC_I2C_SPEED_400_KHZ = 1L
}
I2C communication speed.
Functions
void bc_i2c_init (bc_i2c_channel_t channel, bc_i2c_speed_t speed)
Initialize I2C channel.
bool bc_i2c_write (bc_i2c_channel_t channel, const bc_i2c_tranfer_t *transfer)
Write to I2C channel.
bool bc_i2c_read (bc_i2c_channel_t channel, const bc_i2c_tranfer_t *transfer)
Read from I2C channel.
bool bc_i2c_write_8b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint8_t data)
Write 1 byte to I2C channel.
bool bc_i2c_write_16b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint16_t data)
Write 2 bytes to I2C channel.
bool bc_i2c_read_8b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint8_t *data)
Read 1 byte from I2C channel.
bool bc_i2c_read_16b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint16_t *data)
Read 2 bytes from I2C channel.
Detailed Description
Driver for I2C bus.
Enumeration Type Documentation
enum bc_i2c_channel_t
I2C channels.
Enumerator
BC_I2C_I2C0
I2C channel I2C0.
BC_I2C_I2C1
I2C channel I2C1.
Definition at line 15 of file bc_i2c.h.
enum bc_i2c_speed_t
I2C communication speed.
Enumerator
BC_I2C_SPEED_100_KHZ
I2C communication speed is 100 kHz.
BC_I2C_SPEED_400_KHZ
I2C communication speed is 400 kHz.
Definition at line 24 of file bc_i2c.h.
Function Documentation
void bc_i2c_init (bc_i2c_channel_t channel, bc_i2c_speed_t speed)
Initialize I2C channel.
Parameters
[in] channel I2C channel
[in] speed I2C communication speed
Definition at line 19 of file bc_i2c.c.
Referenced by bc_hdc2080_init(), bc_hts221_init(), bc_lis2dh12_init(), bc_mpl3115a2_init(), bc_opt3001_init(), bc_sc16is740_init(), bc_tca9534a_init(), and bc_tmp112_init().
bool bc_i2c_read (bc_i2c_channel_t channel, const bc_i2c_tranfer_t * transfer)
Read from I2C channel.
Parameters
[in] channel I2C channel
[in] transfer Pointer to I2C transfer parameters instance
Returns
true on success
false on failure
Definition at line 172 of file bc_i2c.c.
Referenced by bc_i2c_read_16b(), bc_i2c_read_8b(), and bc_sc16is740_read().
bool bc_i2c_read_16b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint16_t * data)
Read 2 bytes from I2C channel.
Parameters
[in] channel I2C channel
[in] device_address 7-bit I2C device address
[in] memory_address 8-bit I2C memory address (it can be extended to 16-bit format if OR-ed with BC_I2C_MEMORY_ADDRESS_16_BIT)
[out] data Output data which have been read (MSB first)
Definition at line 251 of file bc_i2c.c.
bool bc_i2c_read_8b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint8_t * data)
Read 1 byte from I2C channel.
Parameters
[in] channel I2C channel
[in] device_address 7-bit I2C device address
[in] memory_address 8-bit I2C memory address (it can be extended to 16-bit format if OR-ed with BC_I2C_MEMORY_ADDRESS_16_BIT)
[out] data Output data which have been read
Definition at line 239 of file bc_i2c.c.
Referenced by bc_sc16is740_available(), bc_sc16is740_get_spaces_available(), bc_sc16is740_init(), bc_tca9534a_get_port_direction(), bc_tca9534a_init(), and bc_tca9534a_read_port().
bool bc_i2c_write (bc_i2c_channel_t channel, const bc_i2c_tranfer_t * transfer)
Write to I2C channel.
Parameters
[in] channel I2C channel
[in] transfer Pointer to I2C transfer parameters instance
Returns
true on success
false on failure
Definition at line 134 of file bc_i2c.c.
Referenced by bc_i2c_write_16b(), bc_i2c_write_8b(), and bc_sc16is740_write().
bool bc_i2c_write_16b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint16_t data)
Write 2 bytes to I2C channel.
Parameters
[in] channel I2C channel
[in] device_address 7-bit I2C device address
[in] memory_address 8-bit I2C memory address (it can be extended to 16-bit format if OR-ed with BC_I2C_MEMORY_ADDRESS_16_BIT)
[in] data Input data to be written (MSB first)
Definition at line 222 of file bc_i2c.c.
bool bc_i2c_write_8b (bc_i2c_channel_t channel, uint8_t device_address, uint32_t memory_address, uint8_t data)
Write 1 byte to I2C channel.
Parameters
[in] channel I2C channel
[in] device_address 7-bit I2C device address
[in] memory_address 8-bit I2C memory address (it can be extended to 16-bit format if OR-ed with BC_I2C_MEMORY_ADDRESS_16_BIT)
[in] data Input data to be written
Definition at line 210 of file bc_i2c.c.
Referenced by bc_lis2dh12_set_alarm(), bc_sc16is740_init(), bc_sc16is740_reset_fifo(), bc_tca9534a_set_port_direction(), and bc_tca9534a_write_port().