Core Module SDK Documentation: bc_tca9534a
bc_tca9534a
Driver for SC16IS740 single UART with I2C-bus interface, 64 bytes of transmit and receive FIFOs.
Data Structures
struct bc_sc16is740_t
TCA9534A instance.
struct bc_tca9534a_t
TCA9534A instance.
Enumerations
enum bc_sc16is740_fifo_t {
BC_SC16IS740_FIFO_RX = 0x02,
BC_SC16IS740_FIFO_TX = 0x04
}
Fifo type.
enum bc_tca9534a_pin_t {
BC_TCA9534A_PIN_P0 = 0,
BC_TCA9534A_PIN_P1 = 1,
BC_TCA9534A_PIN_P2 = 2,
BC_TCA9534A_PIN_P3 = 3,
BC_TCA9534A_PIN_P4 = 4,
BC_TCA9534A_PIN_P5 = 5,
BC_TCA9534A_PIN_P6 = 6,
BC_TCA9534A_PIN_P7 = 7
}
Individual pin names.
enum bc_tca9534a_pin_direction_t {
BC_TCA9534A_PIN_DIRECTION_OUTPUT = 0,
BC_TCA9534A_PIN_DIRECTION_INPUT = 1
}
Pin direction.
enum bc_tca9534a_state_t {
BC_TCA9534A_PIN_STATE_LOW = 0,
BC_TCA9534A_PIN_STATE_HIGH = 1
}
Pin state.
Functions
bool bc_sc16is740_init (bc_sc16is740_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SC16IS740.
bool bc_sc16is740_reset_fifo (bc_sc16is740_t *self, bc_sc16is740_fifo_t fifo)
Reset FIFO.
bool bc_sc16is740_get_spaces_available (bc_sc16is740_t *self, uint8_t *spaces_available)
Get TX FIXO space available.
uint8_t bc_sc16is740_write (bc_sc16is740_t *self, uint8_t *buffer, uint8_t length)
Write.
bool bc_sc16is740_available (bc_sc16is740_t *self, uint8_t *available)
Get RX FIXO available data.
uint8_t bc_sc16is740_read (bc_sc16is740_t *self, uint8_t *buffer, uint8_t length, bc_tick_t timeout)
Read.
bool bc_tca9534a_init (bc_tca9534a_t *self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize TCA9534A.
bool bc_tca9534a_read_port (bc_tca9534a_t *self, uint8_t *state)
Read state of all pins.
bool bc_tca9534a_write_port (bc_tca9534a_t *self, uint8_t state)
Write state to all pins.
bool bc_tca9534a_read_pin (bc_tca9534a_t *self, bc_tca9534a_pin_t pin, bc_tca9534a_state_t *state)
Read pin state.
bool bc_tca9534a_write_pin (bc_tca9534a_t *self, bc_tca9534a_pin_t pin, bc_tca9534a_state_t state)
Write pin state.
bool bc_tca9534a_get_port_direction (bc_tca9534a_t *self, uint8_t *direction)
Get direction of all pins.
bool bc_tca9534a_set_port_direction (bc_tca9534a_t *self, uint8_t direction)
Set direction of all pins.
bool bc_tca9534a_get_pin_direction (bc_tca9534a_t *self, bc_tca9534a_pin_t pin, bc_tca9534a_pin_direction_t *direction)
Get pin direction.
bool bc_tca9534a_set_pin_direction (bc_tca9534a_t *self, bc_tca9534a_pin_t pin, bc_tca9534a_pin_direction_t direction)
Set pin direction.
Detailed Description
Driver for SC16IS740 single UART with I2C-bus interface, 64 bytes of transmit and receive FIFOs.
Driver for TCA9534A I/O expander.
Function Documentation
bool bc_sc16is740_available (bc_sc16is740_t * self, uint8_t * available)
Get RX FIXO available data.
Parameters
[in] self Instance
[out] available
Returns
true on success
false on failure
Definition at line 180 of file bc_sc16is740.c.
Referenced by bc_sc16is740_read().
bool bc_sc16is740_get_spaces_available (bc_sc16is740_t * self, uint8_t * spaces_available)
Get TX FIXO space available.
Parameters
[in] self Instance
[out] spaces_available
Returns
true on success
false on failure
Definition at line 142 of file bc_sc16is740.c.
Referenced by bc_sc16is740_write().
bool bc_sc16is740_init (bc_sc16is740_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize SC16IS740.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Returns
true on success
false on failure
Definition at line 23 of file bc_sc16is740.c.
uint8_t bc_sc16is740_read (bc_sc16is740_t * self, uint8_t * buffer, uint8_t length, bc_tick_t timeout)
Read.
Parameters
[in] self Instance
[out] buffer Pointer to destination buffer
[in] length Number of bytes to be read
[in] timeout Write operation timeout in ticks
Returns
Number of bytes read
Definition at line 185 of file bc_sc16is740.c.
bool bc_sc16is740_reset_fifo (bc_sc16is740_t * self, bc_sc16is740_fifo_t fifo)
Reset FIFO.
Parameters
[in] self Instance
[in] fifo
Returns
true on success
false on failure
Definition at line 135 of file bc_sc16is740.c.
uint8_t bc_sc16is740_write (bc_sc16is740_t * self, uint8_t * buffer, uint8_t length)
Write.
Parameters
[in] self Instance
[in] buffer Pointer to source buffer
[in] length Number of bytes to be written
Returns
Number of bytes written
Definition at line 147 of file bc_sc16is740.c.
bool bc_tca9534a_get_pin_direction (bc_tca9534a_t * self, bc_tca9534a_pin_t pin, bc_tca9534a_pin_direction_t * direction)
Get pin direction.
Parameters
[in] self Instance
[in] pin Pin name
[out] direction Pointer to variable where direction of pin will be stored
Returns
true on success
false on failure
Definition at line 112 of file bc_tca9534a.c.
bool bc_tca9534a_get_port_direction (bc_tca9534a_t * self, uint8_t * direction)
Get direction of all pins.
Parameters
[in] self Instance
[out] direction Pointer to variable where direction of all pins will be stored
Returns
true on success
false on failure
Definition at line 92 of file bc_tca9534a.c.
Referenced by bc_tca9534a_get_pin_direction(), and bc_tca9534a_set_pin_direction().
bool bc_tca9534a_init (bc_tca9534a_t * self, bc_i2c_channel_t i2c_channel, uint8_t i2c_address)
Initialize TCA9534A.
Parameters
[in] self Instance
[in] i2c_channel I2C channel
[in] i2c_address I2C device address
Definition at line 8 of file bc_tca9534a.c.
Referenced by bc_module_lcd_init().
bool bc_tca9534a_read_pin (bc_tca9534a_t * self, bc_tca9534a_pin_t pin, bc_tca9534a_state_t * state)
Read pin state.
Parameters
[in] self Instance
[in] pin Pin name
[out] state Pointer to variable where state of pin will be stored
Returns
true on success
false on failure
Definition at line 47 of file bc_tca9534a.c.
bool bc_tca9534a_read_port (bc_tca9534a_t * self, uint8_t * state)
Read state of all pins.
Parameters
[in] self Instance
[out] state Pointer to variable where state of all pins will be stored
Returns
true on success
false on failure
Definition at line 27 of file bc_tca9534a.c.
Referenced by bc_tca9534a_read_pin(), and bc_tca9534a_write_pin().
bool bc_tca9534a_set_pin_direction (bc_tca9534a_t * self, bc_tca9534a_pin_t pin, bc_tca9534a_pin_direction_t direction)
Set pin direction.
Parameters
[in] self Instance
[in] pin Pin name
[in] direction Desired pin direction
Returns
true on success
false on failure
Definition at line 133 of file bc_tca9534a.c.
bool bc_tca9534a_set_port_direction (bc_tca9534a_t * self, uint8_t direction)
Set direction of all pins.
Parameters
[in] self Instance
[in] direction Desired direction of all pins
Returns
true on success
false on failure
Definition at line 102 of file bc_tca9534a.c.
Referenced by bc_module_lcd_init(), and bc_tca9534a_set_pin_direction().
bool bc_tca9534a_write_pin (bc_tca9534a_t * self, bc_tca9534a_pin_t pin, bc_tca9534a_state_t state)
Write pin state.
Parameters
[in] self Instance
[in] pin Pin name
[in] state Desired state of pin
Returns
true on success
false on failure
Definition at line 68 of file bc_tca9534a.c.
bool bc_tca9534a_write_port (bc_tca9534a_t * self, uint8_t state)
Write state to all pins.
Parameters
[in] self Instance
[in] state Desired state of all pins
Returns
true on success
false on failure
Definition at line 37 of file bc_tca9534a.c.
Referenced by bc_module_lcd_init(), bc_module_lcd_off(), bc_module_lcd_on(), and bc_tca9534a_write_pin().