var modules =
[
    [ "bc_adc", "group__bc__adc.html", "group__bc__adc" ],
    [ "bc_button", "group__bc__button.html", "group__bc__button" ],
    [ "bc_dac", "group__bc__dac.html", "group__bc__dac" ],
    [ "bc_dfu", "group__bc__dfu.html", "group__bc__dfu" ],
    [ "bc_eeprom", "group__bc__eeprom.html", "group__bc__eeprom" ],
    [ "bc_exti", "group__bc__exti.html", "group__bc__exti" ],
    [ "bc_fifo", "group__bc__fifo.html", "group__bc__fifo" ],
    [ "bc_gpio", "group__bc__gpio.html", "group__bc__gpio" ],
    [ "bc_i2c", "group__bc__i2c.html", "group__bc__i2c" ],
    [ "bc_irq", "group__bc__irq.html", "group__bc__irq" ],
    [ "bc_led", "group__bc__led.html", "group__bc__led" ],
    [ "bc_lis2dh12", "group__bc__lis2dh12.html", "group__bc__lis2dh12" ],
    [ "bc_module_pir", "group__bc__module__pir.html", "group__bc__module__pir" ],
    [ "bc_module_power", "group__bc__module__power.html", "group__bc__module__power" ],
    [ "bc_module_relay", "group__bc__module__relay.html", "group__bc__module__relay" ],
    [ "bc_module_sigfox", "group__bc__module__sigfox.html", "group__bc__module__sigfox" ],
    [ "bc_mpl3115a2", "group__bc__mpl3115a2.html", "group__bc__mpl3115a2" ],
    [ "bc_opt3001", "group__bc__opt3001.html", "group__bc__opt3001" ],
    [ "bc_pyq1648", "group__bc__pyq1648.html", "group__bc__pyq1648" ],
    [ "bc_rtc", "group__bc__rtc.html", "group__bc__rtc" ],
    [ "bc_scheduler", "group__bc__scheduler.html", "group__bc__scheduler" ],
    [ "bc_spi", "group__bc__spi.html", "group__bc__spi" ],
    [ "bc_tag_barometer", "group__bc__tag__barometer.html", "group__bc__tag__barometer" ],
    [ "bc_tag_lux_meter", "group__bc__tag__lux__meter.html", "group__bc__tag__lux__meter" ],
    [ "bc_tag_temperature", "group__bc__tag__temperature.html", "group__bc__tag__temperature" ],
    [ "bc_tca9534a", "group__bc__tca9534a.html", "group__bc__tca9534a" ],
    [ "bc_td1207r", "group__bc__td1207r.html", "group__bc__td1207r" ],
    [ "bc_tick", "group__bc__tick.html", "group__bc__tick" ],
    [ "bc_tmp112", "group__bc__tmp112.html", "group__bc__tmp112" ],
    [ "bc_uart", "group__bc__uart.html", "group__bc__uart" ]
];